public with sharing class Util {
    public static final String DESIGN_SERVICES = 'Design Services';
    public static final String RENOVATION_SERVICES = 'Renovation Services';
    public static final String FURNITURE_FITTINGS = 'Furniture & Fittings';
    public static final String FURNISHING_FITTINGS_INSTALLATION = 'Furnishing & Fittings Installation';
    public static final String MATERIALS_SERVICES = 'Materials';
    public static final String INTERIOR_DESIGNER = 'Interior Designer';
    public static final String RENOVATION_SPECIALIST = 'Renovation Specialist';
    public static final String FURNITURE_MAKER = 'Furniture Maker';
    public static final String FURNISHING_INSTALLATION_EXPERT = 'Furnishing & Installation Expert';
    public static final String PENDING = 'Pending';
    public static final String SUCCESS = 'Success';
    public static final String ERROR = 'Error';
    public static final String RETRY_ERROR = 'Retry Error';
    public static final String RETRY_SUCCESS = 'Retry Success';




}